# Generated by Django 3.0 on 2022-04-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20220322_1224'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='follow',
            field=models.ManyToManyField(db_table='follows', related_name='follows', to='employers.Employer'),
        ),
    ]
