# Generated by Django 3.0 on 2022-04-02 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20220322_1224'),
        ('members', '0002_member_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('-user',)},
        ),
        migrations.RemoveField(
            model_name='member',
            name='follow',
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_follows', to='employers.Employer')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_follows', to='members.Member')),
            ],
            options={
                'db_table': 'follows',
                'ordering': ('-pk',),
            },
        ),
    ]
