# Generated by Django 3.0 on 2022-04-07 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_campaign_slug'),
        ('members', '0003_auto_20220402_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_save_jobs', to='jobs.Job')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_save_jobs', to='members.Member')),
            ],
            options={
                'db_table': 'save_jobs',
                'ordering': ('-pk',),
            },
        ),
    ]
