# Generated by Django 3.0 on 2022-03-15 15:30

import api.employers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.employers.models.company_file_upload_file)),
                ('video', models.ImageField(blank=True, null=True, upload_to=api.employers.models.company_file_upload_file)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'company_files',
                'ordering': ('-pk',),
            },
        ),
    ]
