# Generated by Django 3.0 on 2022-03-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20220307_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='package_type',
            field=models.CharField(choices=[('Free', 'free'), ('Basic', 'basic'), ('Advance', 'advance')], default=('Free', 'free'), max_length=255),
        ),
    ]
