# Generated by Django 3.0 on 2022-04-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20220322_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='package_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Advance', 'Advance')], default=('Free', 'Free'), max_length=255),
        ),
    ]
