# Generated by Django 3.0 on 2022-03-31 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('employers', '0002_auto_20220322_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('point', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_review', to='employers.Employer')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_review', to='members.Member')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ('-pk',),
            },
        ),
    ]
