# Generated by Django 3.0 on 2022-03-31 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20220322_1224'),
        ('members', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reviews', to='employers.Employer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_reviews', to='members.Member'),
        ),
    ]
