# Generated by Django 3.0 on 2022-03-05 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_auto_20220305_2308'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.Employer'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobType'),
        ),
        migrations.AddField(
            model_name='job',
            name='tag',
            field=models.ManyToManyField(db_table='jobs_tags', related_name='jobs_tags', to='jobs.Tag'),
        ),
    ]
