# Generated by Django 3.0 on 2022-03-31 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20220322_1224'),
        ('jobs', '0002_auto_20220322_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, choices=[('book', 'book'), ('person', 'person')], default=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'benefits',
                'ordering': ('-pk',),
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.AddField(
            model_name='job',
            name='job_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ManyToManyField(db_table='job_addresses_cities', related_name='job_addresses_cities', to='jobs.City')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_job_address', to='employers.Employer')),
            ],
            options={
                'db_table': 'job_addresses',
                'ordering': ('-pk',),
            },
        ),
    ]
