# Generated by Django 3.0 on 2022-03-31 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20220331_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobaddress',
            name='employer',
        ),
        migrations.AddField(
            model_name='jobaddress',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_job_address', to='jobs.Job'),
            preserve_default=False,
        ),
    ]
