# Generated by Django 3.0 on 2022-03-31 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20220331_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobaddress',
            name='city',
        ),
        migrations.AddField(
            model_name='jobaddress',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_job_address', to='jobs.City'),
            preserve_default=False,
        ),
    ]
