# Generated by Django 3.0 on 2022-03-31 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20220331_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_benefit', to='jobs.Job'),
            preserve_default=False,
        ),
    ]
