# Generated by Django 3.0 on 2022-03-31 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_benefit_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_benefits', to='jobs.Job'),
        ),
    ]
