# Generated by Django 3.0 on 2022-03-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20220331_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefit',
            old_name='name',
            new_name='benefit',
        ),
    ]
