# Generated by Django 3.0 on 2022-03-31 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20220331_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_benefits', to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='jobaddress',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_job_addresses', to='jobs.Job'),
        ),
    ]
