# Generated by Django 3.0 on 2022-03-31 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20220331_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobaddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_job_addresses', to='jobs.City'),
        ),
    ]
