# Generated by Django 3.0 on 2022-04-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20220331_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='benefit',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
