# Generated by Django 3.0 on 2022-04-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_match_cv',
            field=models.BooleanField(default=True),
        ),
    ]
