# Generated by Django 3.0 on 2022-04-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_campaign_is_match_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_jobs', to='jobs.Campaign'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_campaigns', to='jobs.City'),
            preserve_default=False,
        ),
    ]
