# Generated by Django 3.0 on 2022-04-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20220403_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
