# Generated by Django 3.0 on 2022-04-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_auto_20220403_2228'),
        ('jobs', '0016_campaign_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employer_campaigns', to='employers.Employer'),
            preserve_default=False,
        ),
    ]
