# Generated by Django 3.0 on 2022-04-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20220414_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, choices=[('Chưa có kinh nghiệm', 'Chưa có kinh nghiệm'), ('1 năm kinh nghiệm', '1 năm kinh nghiệm'), ('Trên 1 năm kinh nghiệm', 'Trên 1 năm kinh nghiệm'), ('Dưới 1 năm kinh nghiệm', 'Dưới 1 năm kinh nghiệm'), ('2 năm kinh nghiệm', '2 năm kinh nghiệm'), ('Trên 2 năm kinh nghiệm', 'Trên 2 năm kinh nghiệm'), ('Dưới 2 năm kinh nghiệm', 'Dưới 2 năm kinh nghiệm'), ('3 năm kinh nghiệm', '3 năm kinh nghiệm'), ('Trên 3 năm kinh nghiệm', 'Trên 3 năm kinh nghiệm'), ('Dưới 3 năm kinh nghiệm', 'Dưới 3 năm kinh nghiệm'), ('3 năm kinh nghiệm', '3 năm kinh nghiệm'), ('Trên 3 năm kinh nghiệm', 'Trên 3 năm kinh nghiệm'), ('Dưới 3 năm kinh nghiệm', 'Dưới 3 năm kinh nghiệm'), ('4 năm kinh nghiệm', '4 năm kinh nghiệm'), ('Trên 4 năm kinh nghiệm', 'Trên 4 năm kinh nghiệm'), ('Dưới 4 năm kinh nghiệm', 'Dưới 4 năm kinh nghiệm'), ('5 năm kinh nghiệm', '5 năm kinh nghiệm'), ('Trên 5 năm kinh nghiệm', 'Trên 5 năm kinh nghiệm'), ('Dưới 5 năm kinh nghiệm', 'Dưới 5 năm kinh nghiệm')], default=('Chưa có kinh nghiệm', 'Chưa có kinh nghiệm'), max_length=255, null=True),
        ),
    ]
