# Generated by Django 3.0 on 2022-04-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_auto_20220414_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_from',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_to',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('Thương lượng', 'Thương lượng'), ('Lương', 'Lương'), ('Lương khoảng', 'Lương khoảng')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.CharField(blank=True, choices=[('VND', 'vnd'), ('USD', 'dollar')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, choices=[('Chưa có kinh nghiệm', 'Chưa có kinh nghiệm'), ('1 năm kinh nghiệm', '1 năm kinh nghiệm'), ('Trên 1 năm kinh nghiệm', 'Trên 1 năm kinh nghiệm'), ('Dưới 1 năm kinh nghiệm', 'Dưới 1 năm kinh nghiệm'), ('2 năm kinh nghiệm', '2 năm kinh nghiệm'), ('Trên 2 năm kinh nghiệm', 'Trên 2 năm kinh nghiệm'), ('Dưới 2 năm kinh nghiệm', 'Dưới 2 năm kinh nghiệm'), ('3 năm kinh nghiệm', '3 năm kinh nghiệm'), ('Trên 3 năm kinh nghiệm', 'Trên 3 năm kinh nghiệm'), ('Dưới 3 năm kinh nghiệm', 'Dưới 3 năm kinh nghiệm'), ('3 năm kinh nghiệm', '3 năm kinh nghiệm'), ('Trên 3 năm kinh nghiệm', 'Trên 3 năm kinh nghiệm'), ('Dưới 3 năm kinh nghiệm', 'Dưới 3 năm kinh nghiệm'), ('4 năm kinh nghiệm', '4 năm kinh nghiệm'), ('Trên 4 năm kinh nghiệm', 'Trên 4 năm kinh nghiệm'), ('Dưới 4 năm kinh nghiệm', 'Dưới 4 năm kinh nghiệm'), ('5 năm kinh nghiệm', '5 năm kinh nghiệm'), ('Trên 5 năm kinh nghiệm', 'Trên 5 năm kinh nghiệm'), ('Dưới 5 năm kinh nghiệm', 'Dưới 5 năm kinh nghiệm')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(blank=True, choices=[('Nhân viên', 'Nhân viên'), ('Quản lý', 'Quản lý')], max_length=255, null=True),
        ),
    ]
