# Generated by Django 3.0 on 2022-04-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20220414_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.CharField(blank=True, choices=[('VND', 'VND'), ('USD', 'USD')], max_length=100, null=True),
        ),
    ]
