# Generated by Django 3.0 on 2022-03-15 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('view', models.BigIntegerField(blank=True, default=0)),
                ('target_major', models.TextField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'cvs',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Cv_Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'cv_careers',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Cv_Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'cv_designs',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='CvCertificate',
            fields=[
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cvs.Cv')),
                ('name', models.CharField(max_length=255)),
                ('year', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cv_certificaties',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='CvEducation',
            fields=[
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cvs.Cv')),
                ('degree_name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('university_name', models.CharField(max_length=255)),
                ('gpa', models.FloatField()),
                ('starting_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cv_educations',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='CvExperience',
            fields=[
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cvs.Cv')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('job_location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_state', models.CharField(max_length=255)),
                ('job_country', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cv_experiences',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='CvSkill',
            fields=[
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cvs.Cv')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cv_skills',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='CvSocialActivity',
            fields=[
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cvs.Cv')),
                ('title', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('starting_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cv_social_activities',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='cv',
            name='cv_career',
            field=models.ManyToManyField(db_table='cvs_cv_carrers', related_name='cvs_cv_carrers', to='cvs.Cv_Career'),
        ),
        migrations.AddField(
            model_name='cv',
            name='cv_design',
            field=models.ManyToManyField(db_table='cvs_cv_designs', related_name='cvs_cv_designs', to='cvs.Cv_Design'),
        ),
    ]
