# Generated by Django 3.0 on 2022-03-17 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvcertificate',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_cv_certificaties', to='cvs.Cv'),
        ),
        migrations.AlterField(
            model_name='cveducation',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_cv_educations', to='cvs.Cv'),
        ),
        migrations.AlterField(
            model_name='cvexperience',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_cv_experiences', to='cvs.Cv'),
        ),
        migrations.AlterField(
            model_name='cvskill',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_cv_skills', to='cvs.Cv'),
        ),
        migrations.AlterField(
            model_name='cvsocialactivity',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_cv_social_activities', to='cvs.Cv'),
        ),
    ]
