# Generated by Django 3.0 on 2022-03-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_auto_20220317_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvexperience',
            old_name='job_state',
            new_name='job_status',
        ),
    ]
