# Generated by Django 3.0 on 2022-03-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_cv_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvcertificate',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvcertificate',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvexperience',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
