# Generated by Django 3.0 on 2022-03-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0004_auto_20220317_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvexperience',
            name='job_state',
            field=models.BooleanField(),
        ),
    ]
