# Generated by Django 3.0 on 2022-03-17 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0005_auto_20220317_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvcertificate',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_cv_certificates', to='cvs.Cv'),
        ),
        migrations.AlterModelTable(
            name='cvcertificate',
            table='cv_certificates',
        ),
    ]
