# Generated by Django 3.0 on 2022-03-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0006_auto_20220317_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvcertificate',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
