# Generated by Django 3.0 on 2022-03-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0008_auto_20220317_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cveducation',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cveducation',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
