# Generated by Django 3.0 on 2022-03-19 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('cvs', '0009_auto_20220318_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='user',
        ),
        migrations.AddField(
            model_name='cv',
            name='member',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='member_cvs', to='members.Member'),
            preserve_default=False,
        ),
    ]
