# Generated by Django 3.0 on 2022-03-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0010_auto_20220319_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvsocialactivity',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvsocialactivity',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
